-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, concat_ws(" ", CITY, STREET_ADDRESS1, STREET_ADDRESS2) 전체주소, concat_ws("-", left(TLNO, 3), mid(TLNO, 4, 4), right(TLNO, 4)) 전화번호
FROM USED_GOODS_USER
WHERE USER_ID in (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING count(*) >= 3)
ORDER BY USER_ID desc