SELECT A.ANIMAL_ID AS ANIMAL_ID
     , A.ANIMAL_TYPE AS ANIMAL_TYPE
     , A.NAME AS NAME
  FROM ANIMAL_INS A 
  LEFT OUTER JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
 WHERE B.SEX_UPON_OUTCOME != A.SEX_UPON_INTAKE
 ORDER BY ANIMAL_ID ASC