SELECT year(SALES_DATE) YEAR, month(SALES_DATE) MONTH, GENDER, count(distinct USER_ID) USERS
FROM ONLINE_SALE S natural join USER_INFO U
GROUP BY year(SALES_DATE), month(SALES_DATE), GENDER
HAVING GENDER is not null
ORDER BY year(SALES_DATE), month(SALES_DATE), GENDER