-- 코드를 입력하세요
SELECT U.USER_ID, NICKNAME, sum(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
WHERE STATUS = "DONE"
GROUP BY U.USER_ID
HAVING sum(PRICE) >= 700000
ORDER BY 3