SELECT ROUTE, concat(round(sum(D_BETWEEN_DIST), 1), "km") TOTAL_DISTANCE, concat(round(avg(D_BETWEEN_DIST), 2), "km") AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY sum(D_BETWEEN_DIST) desc