WITH TOTAL AS (SELECT USER_ID FROM USER_INFO WHERE year(JOINED) = 2021)

SELECT year(SALES_DATE) YEAR, month(SALES_DATE) MONTH,
    count(distinct USER_ID) PURCHASED_USERS,
    round(count(distinct USER_ID) / (SELECT count(*) FROM TOTAL), 1) PUCHASED_RATIO
FROM ONLINE_SALE S
WHERE USER_ID in (SELECT * FROM TOTAL)
GROUP BY year(SALES_DATE), month(SALES_DATE)
ORDER BY YEAR, MONTH