SELECT YEAR, MONTH, PURCHASED_USERS, round(PURCHASED_USERS / TOTAL, 1) PUCHASED_RATIO
FROM 
    (SELECT year(SALES_DATE) YEAR, month(SALES_DATE) MONTH, count(distinct U.USER_ID) PURCHASED_USERS
    FROM USER_INFO U join ONLINE_SALE S
        on U.USER_ID = S.USER_ID and year(JOINED) = 2021
    GROUP BY year(SALES_DATE), month(SALES_DATE)) P
CROSS JOIN
    (SELECT count(USER_ID) TOTAL
    FROM USER_INFO
    WHERE year(JOINED) = 2021) T
ORDER BY YEAR, MONTH