WITH RECURSIVE GEN AS
    (
        SELECT ID, PARENT_ID, 1 as GENERATION
        FROM ECOLI_DATA
        WHERE PARENT_ID is null
        UNION ALL
        SELECT E.ID, E.PARENT_ID, GENERATION + 1 as GENERATION
        FROM ECOLI_DATA E join GEN G
        ON E.PARENT_ID = G.ID
    )

SELECT count(G1.ID) COUNT, G1.GENERATION
FROM GEN G1 left join Gen G2
    on G1.ID = G2.PARENT_ID
WHERE G2.ID is null
GROUP BY G1.GENERATION
ORDER BY G1.GENERATION