SELECT      A.PRODUCT_ID
        ,   B.PRODUCT_NAME
        ,   SUM(A.AMOUNT)*MAX(B.PRICE) TOTAL_SALES
FROM        FOOD_ORDER      A
        ,   FOOD_PRODUCT    B
WHERE       1=1
            AND A.PRODUCT_ID = B.PRODUCT_ID
            AND TO_CHAR(A.PRODUCE_DATE,'YYYYMM') = '202205'
GROUP BY    A.PRODUCT_ID
        ,   B.PRODUCT_NAME
ORDER BY    3 DESC, 1 ASC