SELECT A.HOUR, NVL(B.CNT,0)
FROM  (SELECT  LEVEL - 1 AS HOUR  FROM    DUAL  CONNECT BY LEVEL <= 24 ) A 
LEFT OUTER JOIN (
SELECT  TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR, COUNT(ANIMAL_ID) AS CNT
  from ANIMAL_OUTS  
  GROUP BY   TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))  ) B
  ON A.HOUR = B.HOUR

 ORDER BY 1 ASC