-- 코드를 입력하세요
SELECT HISTORY_ID,
        round((case
         when RENT >= 90 then RENT * DAILY_FEE * ((100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = "트럭" AND DURATION_TYPE like "90%")) / 100)
         when RENT >= 30 then RENT * DAILY_FEE * ((100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = "트럭" AND DURATION_TYPE like "30%")) / 100)
         when RENT >= 7 then RENT * DAILY_FEE * ((100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = "트럭" AND DURATION_TYPE like "7%")) / 100)
         else RENT * DAILY_FEE end)) FEE
FROM (SELECT HISTORY_ID, DAILY_FEE, (datediff(END_DATE, START_DATE) + 1) RENT 
      FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
      USING (CAR_ID) 
      WHERE CAR_TYPE = "트럭") A
ORDER BY 2 desc, 1 desc