SELECT 
    A.MEMBER_NAME, 
    B.REVIEW_TEXT, 
    TO_CHAR(B.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM
    MEMBER_PROFILE A, 
    REST_REVIEW B,
        (SELECT MEMBER_ID, COUNT(*) AS CNT
         FROM REST_REVIEW
         GROUP BY MEMBER_ID
         ORDER BY CNT DESC
         FETCH FIRST 1 ROW ONLY) C
WHERE A.MEMBER_ID = B.MEMBER_ID
AND A.MEMBER_ID = C.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT