-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM (SELECT APNT_YMD, APNT_NO, PT_NO, PT_NAME, MCDP_CD, MDDR_ID
     FROM APPOINTMENT A JOIN PATIENT P
     USING (PT_NO)
     WHERE APNT_CNCL_YN = "N"
     AND MCDP_CD = "CS") A JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
WHERE date_format(APNT_YMD, "%Y-%m-%d") = "2022-04-13"
ORDER BY APNT_YMD