-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, round(avg(R.REVIEW_SCORE), 2) SCORE
FROM REST_INFO I JOIN REST_REVIEW R
USING (REST_ID)
WHERE I.ADDRESS like "서울%"
GROUP BY I.REST_NAME
ORDER BY SCORE desc, I.FAVORITES desc